version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - all
  django:
    image: registry.gitlab.com/my-life-ua/rest-api
    env_file: django.env
    ports:
      - "8082:8000"
    depends_on:
      - postgres
    networks:
      - all
  react:
    image: registry.gitlab.com/my-life-ua/web-application
    ports:
      - "8081:3000"
    depends_on:
      - django
    networks:
      - all
  darkflow:
    image: registry.gitlab.com/my-life-ua/ml-food-recognition
    ports:
      - "8083:5000"
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
