version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - all
  django:
    image: registry.gitlab.com/my-life-ua/rest-api
    env_file: django.env
    environment:
      - SECRET_KEY=#s6$ds9t*ui7@=2bt77h50w2g&i6n9p#krfb&03jk4v^%_5)i7.
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    ports:
      - "8082:8000"
    depends_on:
      - postgres
    networks:
      - all
  react:
    image: registry.gitlab.com/my-life-ua/web-application
    ports:
      - "8081:3000"
    depends_on:
      - django
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
